version: '3'
services:
  postgres-db:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_db: